version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: unless-stopped